add_rules("plugin.compile_commands.autoupdate", {outputdir = ".vscode"})
add_rules("mode.debug", "mode.release")
includes("third_party/**.lua")
set_languages("c++2b")
task("format")
set_category("plugin")
on_run("format")
set_menu({
	usage = "xmake format",
	description = "Format source code",
})
task_end()
target("core")
	set_kind("static")
	add_cxflags("-Wall")
	add_includedirs("$(projectdir)")
	add_cxflags("-stdlib=libc++","-fmodules")
	add_ldflags("-stdlib=libc++","-fmodules")
	set_toolset("cxx", "clang")
	set_toolset("ld", "clang++")
	add_files("src/**.ixx", { install = true })
	add_files("src/**.cpp")
	set_policy("build.c++.modules", true)

includes("example/**.lua")
