set_languages("c++23")
add_rules("plugin.compile_commands.autoupdate", { outputdir = "build" })

set_toolchains("clang")
target("viole-plugin")
set_kind("shared")
add_cxflags("-Wall", "-std=gnu++17", "-fPIC", "-fno-rtti", "-fdiagnostics-color=always", "-fvisibility-inlines-hidden")
add_ldflags("-fPIC", "-fno-rtti")
add_files("src/**.cpp")
add_includedirs("$(projectdir)/include/", "$(projectdir)/plugin/include/")
set_targetdir("$(projectdir)/plugin/dist")
set_basename("viole-plugin")
